use Spotify	;
select * from Users;
select * from Playlists;
select *from tracks;
select *from Users Inner Join Playlists on Playlists.user_id= Users.user_id;
select* from users  Join Tracks on Users.user_id=Tracks.t_id;
select *from Users Left Join Playlists on Playlists.user_id= Users.user_id;
select *from Users Right Join Playlists on Playlists.user_id= Users.user_id;
select *from Users  Join Playlists on Playlists.user_id= Users.user_id;
select *from Users cross Join Playlists ;
select *from Users  Join Playlists on Playlists.user_id= Users.user_id join Tracks on Playlists.p_id=Tracks.p_id;
select *from Users  Left Join Playlists on Playlists.user_id= Users.user_id left join Tracks on Playlists.p_id=Tracks.p_id;
select *from Users  Right Join Playlists on Playlists.user_id= Users.user_id right join Tracks on Playlists.p_id=Tracks.p_id;
select *from Users cross Join Playlists cross join Tracks ;
DELETE Playlists,Tracks FROM Playlists  INNER JOIN Tracks  ON Playlists.p_id=Tracks.p_id WHERE Tracks.t_name='ashapasam'; 
select p_id from Playlists where p_id=1; 