use Spotify	;
select * from Users;
select * from Playlists;
select *from Users Inner Join Playlists on Playlists.user_id= Users.user_id;
select *from Users Left Join Playlists on Playlists.user_id= Users.user_id;
select *from Users Right Join Playlists on Playlists.user_id= Users.user_id;
select *from Users  Join Playlists on Playlists.user_id= Users.user_id;
select *from Users cross Join Playlists ;
select *from Users  Join Playlists on Playlists.user_id= Users.user_id join Tracks on Playlists.p_id=Tracks.p_id;
select *from Users  Left Join Playlists on Playlists.user_id= Users.user_id left join Tracks on Playlists.p_id=Tracks.p_id;
select *from Users  Right Join Playlists on Playlists.user_id= Users.user_id right join Tracks on Playlists.p_id=Tracks.p_id;
select *from Users cross Join Playlists cross join Tracks ;
