show databases;

create database Spotify;
use Spotify;
create table Users(user_id int primary key,user_name varchar(30),u_email varchar(30),u_password varchar(30));
desc Users;
create table Playlists(p_id int primary key,p_name varchar (30),p_desc varchar(40),user_id int, foreign key(user_id) references Users(user_id));
desc Playlists;
insert into Users values (100,'Rajeshwari','raji@gmail.com','R1234567'),(101,'Deeraj','deeraj@gmail.com','D1234567'),(103,'yash','yash@gmail.com','Y1234567');
insert into Users values (102,'GBR','gbr@gmail.com','B1234567');
select * from Users;
insert into Playlists values (1,'Fav','global',100),(2,'BTS','global',100);
select * from Playlists;
create table Tracks(t_id int primary key,t_name varchar(30),t_artist varchar(30),p_id int,foreign key(p_id) references Playlists(p_id));
insert into Tracks values (1,'music','gbr','1');
select * from Tracks;
UPDATE Tracks SET t_artist = 'GBR' WHERE t_id =1;  
DELETE FROM Playlists WHERE p_name = 'BTS';
insert into Playlists values (2,'English','global',100),(3,'BTS','albums',101);
insert into Tracks values (2,'left','charlie',1),(3,'run','jk',2),(4,'ashapasam','siri',3);
SELECT * FROM Users WHERE user_id IN(SELECT user_id FROM Users);
SELECT * FROM Users WHERE user_id IN(SELECT user_id FROM Users WHERE user_id>100);
SELECT * FROM Users WHERE user_id IN(SELECT MAx(user_id) FROM Users );
SELECT * FROM Users WHERE user_id IN(SELECT min(user_id) FROM Users );
SELECT * FROM Users WHERE user_id NOT IN(SELECT user_id FROM Users WHere user_id=102 );
SELECT * FROM Users WHERE user_id IN(SELECT user_id FROM Playlists Where user_id=100 );
SELECT * FROM Playlists WHERE p_id IN(SELECT p_id FROM Playlists Where p_id=1 );
select * from Playlists;
select * from Tracks;
select * from Tracks where Tracks.p_id in (select Playlists.p_id from playlists where Playlists.p_name='Fav');
select * from Tracks where Tracks.p_id in (select Playlists.p_id from playlists where Playlists.p_id=1);
select * from Users where Users.user_id in (select Playlists.user_id from playlists where Playlists.p_name='Fav');
select * from Users where Users.user_id in(select Playlists.user_id from playlists where Playlists.p_id in (select Tracks.p_id from Tracks where tracks.p_id=1));
select * from Users where Users.user_id in(select Playlists.user_id from playlists where Playlists.p_id in (select Tracks.p_id from Tracks where tracks.t_id=4));
select * from Playlists;
select * from Tracks;
select * from Users where Users.user_id in(select Playlists.user_id from playlists where Playlists.p_id in (select Tracks.p_id from Tracks where tracks.p_id=3));
create Table UserDetails(id int primary key,name varchar(30),email varchar(30),gender varchar(10));
insert into UserDetails values (1,'Raji','raji@gmail.com','F'),(2,'Deeraj','Dee@gmail.com','M');
select * from Userdetails;
ALTER TABLE Userdetails ADD Country varchar(30) AFTER gender ;  
 Update Userdetails set Country='India' where id =1;
 Update Userdetails set Country='USA' where id =2;
 RENAME TABLE UserDetails TO subscribers;
 SELECT * FROM subscribers;
 SELECT DISTINCT name from subscribers;
 SELECT DISTINCT name from subscribers where Country='india';
 INSERT INTO subscribers VALUES(3,'JK','Jk@gmail.com','M','India'),(4,'sai','sai@gmail.com','M','USA'),(5,'chinni','ch@gmail.com','F','Switzerland'),(6,'Frank','fr@gmail.com','F','Vennice'),(7,'worldstar','ws@gmail.com','M','Korea');
 SELECT * FROM subscribers where country='India' order by name;
SELECT * FROM subscribers where gender='M' group by name having min(id) >2; 
SELECT * FROM subscribers where gender='M' group by name having Sum(id) >=2; 

EXPLAIN subscribers;